# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_word', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordPratice',
            new_name='WordPractice',
        ),
    ]
